# Generated by Django 5.1.4 on 2026-05-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('candidates', '0002_candidateprofile_election_country_and_more'),
        ('consultants', '0002_consultantprofile_academic_titles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consultant_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='consultants.consultantservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='marketplace_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='candidates.marketplacebid'),
        ),
    ]
