# Generated by Django 5.1.4 on 2026-05-29 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('catalog', '0002_category_parent'),
        ('consultants', '0002_consultantprofile_academic_titles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='election_country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='election_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='election_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='election_level',
            field=models.CharField(blank=True, help_text='national, regional, local, etc.', max_length=40),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='interest_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='subscribed_category_slugs',
            field=models.JSONField(blank=True, default=list, help_text='Categories for marketplace offer email alerts.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='verification_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MarketplaceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_deadline_days', models.PositiveIntegerField(default=30)),
                ('max_budget_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('needs_edit', 'Needs edit'), ('manual_review', 'Manual review')], db_index=True, default='pending', max_length=20)),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_requirements', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_requirements', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_days', models.PositiveIntegerField()),
                ('max_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_bids', to='consultants.consultantprofile')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='candidates.marketplacerequirement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
