# Generated by Django 5.1.4 on 2026-05-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDiagnosticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('scope', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('local', 'Local')], max_length=20)),
                ('election_date', models.DateField()),
                ('district', models.CharField(blank=True, max_length=160)),
                ('retrieved_doc_ids', models.JSONField(default=list)),
                ('retrieval_scores', models.JSONField(default=list)),
                ('cronograma', models.JSONField(default=dict)),
                ('llm_narrative', models.TextField(blank=True)),
                ('llm_model', models.CharField(blank=True, max_length=80)),
                ('llm_mode', models.CharField(blank=True, help_text='openai | rules_fallback', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_diagnostic_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('district', models.CharField(blank=True, db_index=True, max_length=160)),
                ('scope', models.CharField(blank=True, help_text='national | regional | local or empty for generic', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='seed', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country_code', 'title'],
                'indexes': [models.Index(fields=['country_code', 'scope'], name='campaign_di_country_045e8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'title'), name='uniq_knowledge_country_title')],
            },
        ),
    ]
