# Generated by Django 5.1.4 on 2026-05-29 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_parent'),
        ('consultants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='academic_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='cv_approved_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='cv_draft',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='election_levels_interest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='identity_document',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='interest_cities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='interest_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='payout_account_number',
            field=models.CharField(blank=True, help_text='Bank account or wallet ID to receive payouts (USD).', max_length=80),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='verification_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual review')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsultantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accepts_counteroffer', models.BooleanField(default=True)),
                ('requests_clarification', models.BooleanField(default=False, help_text='If true, clarification requests are emailed to the candidate.')),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('pending_ai', 'Pending AI review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual review')], db_index=True, default='draft', max_length=20)),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultant_services', to='catalog.category')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='consultants.consultantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantCommunityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_quality_score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_ratings', to='consultants.consultantprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('consultant', 'reviewer'), name='unique_consultant_reviewer_rating')],
            },
        ),
    ]
