# Generated by Django 5.1.4 on 2026-06-19 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_provider_nullable_fields'),
        ('consultants', '0004_consultantprofile_social_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultantcommunityrating',
            name='unique_consultant_reviewer_rating',
        ),
        migrations.AddField(
            model_name='consultantcommunityrating',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_ratings', to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='consultantcommunityrating',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('reviewer', 'booking'), name='unique_reviewer_booking_rating'),
        ),
    ]
